name: GitHub Profile Summary Cards

on:
  schedule:
    - cron: "17 2 * * *"
      timezone: "Asia/Ho_Chi_Minh"
  workflow_dispatch:

permissions:
  contents: write

concurrency:
  group: profile-summary-cards
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    name: Generate profile summary cards

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Generate cards
        uses: vn7n24fzkq/github-profile-summary-cards@release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          USERNAME: ${{ github.repository_owner }}
          BRANCH_NAME: "main"
          UTC_OFFSET: 7
          EXCLUDE: ""
          AUTO_PUSH: true
