name: Generate Snake

on:
  schedule:
    - cron: "23 2 * * *"
      timezone: "Asia/Ho_Chi_Minh"
  workflow_dispatch:
  push:
    branches:
      - main

permissions:
  contents: write

concurrency:
  group: generate-snake
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    name: Generate contribution snake

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Generate snake assets
        uses: Platane/snk@v3
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: |
            dist/github-snake.svg?color_snake=#ff00ff&color_dots=#161b22,#00ffff,#00cccc,#009999,#006666
            dist/github-snake-dark.svg?palette=github-dark&color_snake=#ff00ff&color_dots=#161b22,#00ffff,#00cccc,#009999,#006666
            dist/ocean.gif?color_snake=#ff00ff&color_dots=#161b22,#00ffff,#00cccc,#009999,#006666

      - name: Publish snake assets
        uses: crazy-max/ghaction-github-pages@v5
        with:
          target_branch: output
          build_dir: dist
          commit_message: "chore: update contribution snake"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
