name: Update README

on:
  schedule:
    - cron: "29 2 * * *"
      timezone: "Asia/Ho_Chi_Minh"
  workflow_dispatch:

permissions:
  contents: write

concurrency:
  group: update-readme-activity
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    name: Update profile README activity

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Update recent GitHub activity
        uses: jamesgeorge007/github-activity-readme@v0.5.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          GH_USERNAME: ${{ github.repository_owner }}
          COMMIT_MSG: "chore: update README activity"
          MAX_LINES: 5
